import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { buildOpenApiDocument } from "./api-contract.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OPENAPI_PATH = resolve(ROOT, "packages/protocol/openapi.json");
const TYPESCRIPT_PATH = resolve(ROOT, "packages/protocol/src/openapi.generated.ts");
const SDK_SCHEMA_PATH = resolve(ROOT, "packages/sdk/src/generated/schema.ts");

const args = new Set(process.argv.slice(2));
for (const arg of args) {
  if (arg !== "--check") throw new Error(`unknown argument: ${arg}`);
}

function sortObject(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortObject);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
      .map(([key, child]) => [key, sortObject(child)]),
  );
}

const document = sortObject(buildOpenApiDocument());
const json = `${JSON.stringify(document, null, 2)}\n`;
const typescript = `// Generated by scripts/generate-api.ts. Do not edit by hand.\n\nexport const OPENAPI_DOCUMENT = ${JSON.stringify(document, null, 2)} as const;\n\nexport type OpenApiDocument = typeof OPENAPI_DOCUMENT;\n`;
const sdkAst = await openapiTS(document as Parameters<typeof openapiTS>[0], {
  alphabetize: true,
  // Request defaults are optional on the wire. Response schemas in http.ts explicitly make their
  // normalized fields required, so inferring requiredness from `default` would only harm inputs.
  defaultNonNullable: false,
  exportType: true,
  immutable: true,
  rootTypes: true,
  silent: true,
});
const sdkSchema = `${astToString(sdkAst).trimEnd()}\n`;

async function differs(path: string, expected: string): Promise<boolean> {
  try {
    return (await readFile(path, "utf8")) !== expected;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
    throw error;
  }
}

if (args.has("--check")) {
  const stale = [
    [OPENAPI_PATH, json],
    [TYPESCRIPT_PATH, typescript],
    [SDK_SCHEMA_PATH, sdkSchema],
  ] as const;
  const mismatches: string[] = [];
  for (const [path, expected] of stale) {
    if (await differs(path, expected)) mismatches.push(path);
  }
  if (mismatches.length) {
    for (const path of mismatches) console.error(`generated API artifact is stale: ${path}`);
    console.error("run: pnpm generate:api");
    process.exitCode = 1;
  } else {
    console.log("generated API artifacts are up to date");
  }
} else {
  await mkdir(dirname(SDK_SCHEMA_PATH), { recursive: true });
  await writeFile(OPENAPI_PATH, json);
  await writeFile(TYPESCRIPT_PATH, typescript);
  await writeFile(SDK_SCHEMA_PATH, sdkSchema);
  console.log(`generated ${OPENAPI_PATH}`);
  console.log(`generated ${TYPESCRIPT_PATH}`);
  console.log(`generated ${SDK_SCHEMA_PATH}`);
}
